export const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER',
  VIEWER: 'VIEWER'
};

export const RESOURCES = {
  DASHBOARD: 'dashboard',
  PRODUCTION: 'production',
  PRODUCTION_UNITS: 'production-units',
  PRODUCTION_CHARGES: 'production-charges',
  CONSUMPTION: 'consumption',
  CONSUMPTION_UNITS: 'consumption-units',
  ALLOCATION: 'allocation',
  BANKING: 'banking',
  LAPSE: 'lapse',
  CAPTIVE: 'captive',
  COMPANY: 'company',
  REPORTS: 'reports',
  INVOICE: 'invoice',
  USERS: 'users',
  ROLES: 'roles'
};

export const ACTIONS = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPERADMIN]: {
    [RESOURCES.DASHBOARD]: [ACTIONS.READ],
    [RESOURCES.PRODUCTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PRODUCTION_UNITS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PRODUCTION_CHARGES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CONSUMPTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CONSUMPTION_UNITS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ALLOCATION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.BANKING]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.LAPSE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CAPTIVE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.COMPANY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.REPORTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ROLES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE]
  },
  [ROLES.ADMIN]: {
    [RESOURCES.DASHBOARD]: [ACTIONS.READ],
    [RESOURCES.PRODUCTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PRODUCTION_UNITS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PRODUCTION_CHARGES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CONSUMPTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CONSUMPTION_UNITS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ALLOCATION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.BANKING]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.LAPSE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CAPTIVE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.COMPANY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.REPORTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ROLES]: [ACTIONS.READ]
  },
  [ROLES.USER]: {
    [RESOURCES.DASHBOARD]: [ACTIONS.READ],
    [RESOURCES.PRODUCTION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRODUCTION_UNITS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRODUCTION_CHARGES]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CONSUMPTION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CONSUMPTION_UNITS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.ALLOCATION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.REPORTS]: [ACTIONS.READ]
  },
  [ROLES.VIEWER]: {
    [RESOURCES.DASHBOARD]: [ACTIONS.READ],
    [RESOURCES.PRODUCTION]: [ACTIONS.READ],
    [RESOURCES.PRODUCTION_UNITS]: [ACTIONS.READ],
    [RESOURCES.PRODUCTION_CHARGES]: [ACTIONS.READ],
    [RESOURCES.CONSUMPTION]: [ACTIONS.READ],
    [RESOURCES.CONSUMPTION_UNITS]: [ACTIONS.READ],
    [RESOURCES.ALLOCATION]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.REPORTS]: [ACTIONS.READ]
  }
};
